<?php

# Fonction qui renvoie le code HTML du menu de toutes les pages
function menu() {
	$menu ='<ul>
			<li><a href="?action=accueil">Accueil</a></li>
			<li><a href="?action=analyse">Analyse du contenue </a></li>
			<li><a href="?action=crud">CRUD</a></li>
			</ul>
			';
	return $menu;
}

function footer(){
	$footer = '<p id="copyright">Generated by Diallo Abdoulaye &copy</p>';
	return $footer;
}

function headerr(){
	$header = '
				<!DOCTYPE html>
				<html>
				<head>
					<style type="text/css">
						#madiv{height:250pt;overflow:auto}
					</style> 
					<link rel="stylesheet" href="css/moncss.css">
					<link rel="stylesheet" href="css/model01.css">
					<link rel="stylesheet" href="css/table.css">
					<title>Projet SGBD</title>
					<meta http-equiv="content-type" content="text/html"; charset="iso-8859-1" />
				</head>
	
	';
	return $header;
}

// fonction qui renvoie le nom des tables de la bd dans une liste déroulante.
function choix_tables($tab){

	$menuChoixTableEtOperation = '	<form id ="formulaire" action="" method ="POST">';
	$menuDeSelectionTable = '<select name="choixTables">';
	for ($i=0;$i<count($tab);$i++) {			  
		$menuDeSelectionTable .=	 '<option>'.$tab[$i].'</option>';	
	}
	$menuDeSelectionTable .= '</select>';
	$menuChoixTableEtOperation	.='<p>Choix de la table '.$menuDeSelectionTable.'<input type="submit" value="Afficher la table"></p></form>';
			
			
	return $menuChoixTableEtOperation;
									  
}

/*
***********************************************************Days of WEEKS********************************************************************************
*/
function select_idDay($tab){

	$resultat = '<select name="choixIdDay">';
	for ($i=0;$i<count($tab);$i++) {			  
		$resultat .=	 '<option>'.$tab[$i]['idDay'].'</option>';
	}
	$resultat .= '</select>';
	return $resultat;
}

// fonction qui va afficher toutes les opérations à effectuer sur la table daysofweek
function crud_dayOfWeeks($tab){
	$resultat = '	
					<fieldset class="block">
						<legend>Ajouter</legend>
							ID : '.increment_daysOfWeekID() .'<br>
					Label: <input type="text" name="labelDaysOfWeekInput"><input type="submit" name="ajouterLabelDaysOfWeek" value="Ajouter"><br>
					</fieldset>
					<fieldset>
						<legend>Modifier</legend>
							ID du jour a modifier : '.select_idDay(listeIdDaysOfWeek()).'<br>
							Nouveau label : <input type="text" name="nouveauLabelDaysOfWeek"><input type="submit" name="modifieridDayDaysOfWeek" value="Modifier">
					</fieldset>
					<table id="tableBalises">
						<thead>
							<tr>
								<th>ID du jour</th>
								<th>Jour</th>
								</tr>
						</thead>
						<tbody>';
				 
	foreach($tab as $elt) {
		$resultat .=		'<tr>';
		$resultat .=		'<td>'.$elt['idDay'].'</td>';
		$resultat .=		'<td>'.$elt['Label'] .'</td>';
		$resultat .=		'</tr>';	 
	}
		
	$resultat .= '	
					</tbody>
					</thead>
				   </table>';			   
	return $resultat;
}

/*
***********************************************************PLAYERS*********************************************************************************
*/

// fonction qui renvoi les idPlayer de la table players dans un menu déroulant
function select_idPlayer($tab){

	$resultat = '<select name="choixIdPlayer">';
	for ($i=0;$i<count($tab);$i++) {			  
		$resultat .=	 '<option>'.$tab[$i]['idPlayer'].'</option>';
	}
	$resultat .= '</select>';
	return $resultat;
}


// fonction qui va afficher toutes les opérations à effectuer sur la table players
function crud_players($tab){
	$resultat = '	
						<fieldset class="block">
							<h3 class="block">Ajouter</h3>
						ID auto-inc : 						'.increment_playersID() .'<br>
						Name : 					<br>		<input type="text" name="nameInPlayersInput"><br>
						Firstname : 			<br>		<input type="text" name="firstnameInPlayersInput"><br>
						Birthdate YYYY-MM-DD :  <br>		<input type="text" name="birthdateInPlayersInput"><br>
						Email : 				<br>		<input type="text" name="emailInPlayersInput"><br>
						Active : 				<br>		<input type="text" name="activeInPlayersInput"><br>
													<input type="submit" name="ajouterChampsInPlayers" value="Ajouter"><br>
						
						<h3>Modifier</h3>
							ID du joueur a modifier :  '.select_idPlayer(listeIdPlayers()).'<br>
							New name :  			  <br> <input type="text" name="newNamePlayers"><br>
							New firstname : 		  <br> <input type="text" name="newFirstNamePlayers"><br>
							New birthdate YYYY-MM-DD :<br> <input type="text" name="newBirthDatePlayers"><br>
							New email : 			  <br><input type="email" name="newEmailPlayers"><br>
							New active : 			  <br> <input type="text" name="newActivePlayers"><br>
													  <br> <input type="submit" name="modifierChampsInPlayers" value="Modifier">
					</fieldset>
					<p></p>
					<table id="tableBalises">
						<thead>
							<tr>
								<th>ID du joueur</th>
								<th>Nom</th>
								<th>Prenom</th>
								<th>Date de naissance</th>
								<th>Email</th>
								<th>Active</th>
								<th>Operation</th>
								</tr>
						</thead>
						<tbody>';
		foreach($tab as $elt){
			$resultat .=		'<tr>';				
			$resultat .=		'<td>'.$elt['idPlayer'].'</td>';
			$resultat .=		'<td>'.$elt['name'].'</td>';
			$resultat .=		'<td>'.$elt['firstname'].'</td>';
			$resultat .=		'<td>'.$elt['birthdate'].'</td>';
			$resultat .=		'<td>'.$elt['email'].'</td>';
			$resultat .=		'<td>'.$elt['active'].'</td>';
			
			if($elt['active'] == 1){
			$resultat .='<td><input type="submit" class="inactif" name="supprimerChampsInPlayers" value="Rendre Inactif"><input type="radio"  name="idPlayerPlayers" value='.$elt['idPlayer'].'>'.'</td>';
			}else{
			$resultat .='<td><input type="submit" class="actif" name="supprimerChampsInPlayers" value="Rendre   Actif"><input type="radio"  name="idPlayerPlayers" value='.$elt['idPlayer'].'>'.'</td>';
			}
		$resultat .=		'</tr>';	
		}
	$resultat .= '	
					</tbody>
					</thead>
				   </table>
				   </form>';			   
	return $resultat;
}

/*
************************************************************RoleType*************************************************************************************************************
*/

// fonction qui renvoi les idPlayer de la table players dans un menu déroulant
function select_idRoleType($tab){

	$resultat = '<form id="formulaire" action="" method="POST">';
	$resultat .= '<select name="choixIdRoleType">';
	for ($i=0;$i<count($tab);$i++) {			  
		$resultat .=	 '<option>'.$tab[$i]['roleTypeId'].'</option>';
	}
	$resultat .= '</select>';
	return $resultat;
}

// fonction qui va afficher toutes les opérations à effectuer sur la table daysofweek
function crud_roletypes($tab){
	$resultat = '	<form id="formulaire" action="?action=crud" method ="POST">
					<fieldset>
						<legend>Ajouter</legend>
					ID : 					'.increment_roletypeID() .'<br>
					Label : 				<br><input type="text" name="labelInRoleTypeInput"><br>
					Ordre : 				<br><input type="text" name="ordreInRoleTypeInput"><br>
					Active :  				<br><input type="text" name="activeInRoleTypeInput"><br>
												<input type="submit" name="ajouterChampsInRoleType" value="Ajouter"><br>
					</fieldset>
					<fieldset>
						<legend>Modifier</legend>
							ID roleType a modifier : '.select_idRoleType(listeIdRoleType()).'<br>
							New Label :  	<br><input type="text" name="newLabelRoleType"><br>
							New ordre : 	<br><input type="text" name="newOrdreRoleType"><br>
							New active : 	<br><input type="text" name="newActiveRoleType"><br>
											<input type="submit" name="modifierChampsInRoleType" value="Modifier">
					</fieldset>
					<table id="tableBalises">
						<thead>
							<tr>
								<th>ID</th>
								<th>Label</th>
								<th>Ordre</th>
								<th>Active</th>
								<th>Cocher pour l\'action</th>
								</tr>
						</thead>
						<tbody>';
				 
	foreach($tab as $elt) {
		$resultat .=		'<tr>';
		$resultat .=		'<td>'.$elt['roleTypeId'].'</td>';
		$resultat .=		'<td>'.$elt['label'] .'</td>';
		$resultat .=		'<td>'.$elt['ordre'] .'</td>';
		$resultat .=		'<td>'.$elt['active'] .'</td>';
		if($elt['active'] == 1){
			$resultat .='<td><input type="submit" class="inactif" name="supprimerChampsInRoleType" value="Rendre Inactif"><input type="radio"  name="idRoleTypeRoletype" value='.$elt['roleTypeId'].'>'.'</td>';
			}else{
			$resultat .='<td><input type="submit" class="actif" name="supprimerChampsInRoleType" value="Rendre   Actif"><input type="radio"  name="idRoleTypeRoletype" value='.$elt['roleTypeId'].'>'.'</td>';
			}
		$resultat .=		'</tr>';	 
	}
		
	$resultat .= '	
					</tbody>
					</thead>
				   </table>
				   </form>';			   
	return $resultat;
}

/*
***********************************************************Staffs****************************************************************************************************
*/

function select_idStaffs($tab){

	$resultat = '<form id="formulaire" action="" method="POST">';
	$resultat .= '<select name="choixIdStaffs">';
	for ($i=0;$i<count($tab);$i++) {			  
		$resultat .=	 '<option>'.$tab[$i]['idStaff'].'</option>';
	}
	$resultat .= '</select>';
	return $resultat;
}

// fonction qui va afficher toutes les opérations à effectuer sur la table daysofweek
function crud_staffs($tab){
	$resultat = '	<form id="formulaire" action="?action=crud" method ="POST">
					<fieldset>
						<legend>Ajouter</legend>
					ID : 						'.increment_staffsID() .'<br>
					Label : 					<br><input type="text" name="labelInStaffsInput"><br>
					Ordre : 					<br><input type="text" name="ordreInStaffsInput"><br>
					ShowInMenu :  				<br><input type="text" name="showInMenuInStaffsInput"><br>
					Active : 					<br><input type="text" name="activeInStaffsInput"><br>
												<input type="submit" name="ajouterChampsInStaffs" value="Ajouter"><br>
					</fieldset>
					<fieldset>
						<legend>Modifier</legend>
							ID roleType a modifier : '.select_idStaffs(listeIdStaffs()).'<br>
							New Label :  		<br><input type="text" name="newLabelStaffs"><br>
							New ordre : 		<br><input type="text" name="newOrdreStaffs"><br>
							New ShowInMenu :	<br><input type="text" name="newShowInMenuStaffs"><br>
							New active : 		<br><input type="text" name="newActiveStaffs"><br>
												<input type="submit" name="modifierChampsInStaffs" value="Modifier">
					</fieldset>
					<table id="tableBalises">
						<thead>
							<tr>
								<th>ID</th>
								<th>Label</th>
								<th>Ordre</th>
								<th>ShowInMenu</th>
								<th>Active</th>
								<th>Operation</th>
								</tr>
						</thead>
						<tbody>';
				 
	foreach($tab as $elt) {
		$resultat .=		'<tr>';
		$resultat .=		'<td>'.$elt['idStaff'].'</td>';
		$resultat .=		'<td>'.$elt['label'] .'</td>';
		$resultat .=		'<td>'.$elt['ordre'] .'</td>';
		$resultat .=		'<td>'.$elt['showInMenu'] .'</td>';
		$resultat .=		'<td>'.$elt['active'] .'</td>';
		if($elt['active'] == 1){
			$resultat .='<td><input type="submit" class="inactif" name="supprimerChampsInStaffs" value="Rendre Inactif"><input type="radio"  name="idStaffStaffs" value='.$elt['idStaff'].'>'.'</td>';
			}else{
			$resultat .='<td><input type="submit" class="actif" name="supprimerChampsInStaffs" value="Rendre   Actif"><input type="radio"  name="idStaffStaffs" value='.$elt['idStaff'].'>'.'</td>';
			}
		$resultat .=		'</tr>';	 
	}
		
	$resultat .= '	
					</tbody>
					</thead>
				   </table>
				   </form>';			   
	return $resultat;
}


/*
************************************************************Users*********************************************************************************************************
*/

function select_idUsers($tab){

	$resultat = '<form id="formulaire" action="" method="POST">';
	$resultat .= '<select name="choixIdUsers">';
	for ($i=0;$i<count($tab);$i++) {			  
		$resultat .=	 '<option>'.$tab[$i]['idUser'].'</option>';
	}
	$resultat .= '</select>';
	return $resultat;
}

// fonction qui va afficher toutes les opérations à effectuer sur la table daysofweek
function crud_users($tab){
	$resultat = '	<form id="formulaire" action="?action=crud" method ="POST">
					<fieldset>
						<legend>Ajouter</legend>
					ID : 						'.increment_usersID() .'<br>
					Nom : 						<br><input type="text" name="nameInUsersInput"><br>
					Prenom :					<br><input type="text" name="firstnameInUsersInput"><br>
					Mail : 						<br><input type="email" name="mailInUsersInput"><br>
					PW : 						<br><input type="text" name="passwordInUsersInput"><br>
					Active : 					<br><input type="text" name="activeInUsersInput"><br>
												<input type="submit" name="ajouterChampsInUsers" value="Ajouter"><br>
					</fieldset>
					<fieldset>
						<legend>Modifier</legend>
							ID users a modifier : '.select_idUsers(listeIdUsers()).'<br>
							New Name :  		<br><input type="text" name="newNameUsers"><br>
							New Firstname : 	<br><input type="text" name="newFirstNameUsers"><br>
							New Mail :			<br><input type="email" name="newMailUsers"><br>
							New PW :			<br><input type="text" name="newPassWordUsers"><br>
							New active : 		<br><input type="text" name="newActiveUsers"><br>
												<input type="submit" name="modifierChampsInUsers" value="Modifier">
					</fieldset>
					<table id="tableBalises">
						<thead>
							<tr>
								<th>ID</th>
								<th>Nom</th>
								<th>Prenom</th>
								<th>Mail</th>
								<th>Mot de passe</th>
								<th>Active</th>
								<th>Operation</th>
								</tr>
						</thead>
						<tbody>';
				 
	foreach($tab as $elt) {
		$resultat .=		'<tr>';
		$resultat .=		'<td>'.$elt['idUser'].'</td>';
		$resultat .=		'<td>'.$elt['name'] .'</td>';
		$resultat .=		'<td>'.$elt['firstname'] .'</td>';
		$resultat .=		'<td>'.$elt['mail'] .'</td>';
		$resultat .=		'<td>'.$elt['password'] .'</td>';
		$resultat .=		'<td>'.$elt['active'] .'</td>';
		if($elt['active'] == 1){
			$resultat .='<td><input type="submit" class="inactif" name="supprimerChampsInUsers" value="Rendre Inactif"><input type="radio"  name="idUsersUser" value='.$elt['idUser'].'>'.'</td>';
			}else{
			$resultat .='<td><input type="submit" class="actif" name="supprimerChampsInUsers" value="Rendre   Actif"><input type="radio"  name="idUsersUser" value='.$elt['idUser'].'>'.'</td>';
			}
		$resultat .=		'</tr>';	 
	}
		
	$resultat .= '	
					</tbody>
					</thead>
				   </table>
				   </form>';			   
	return $resultat;
}

/************************************************************************************************************************************************************************************/


/*
************************************************************Teams*********************************************************************************************************
*/

function select_idTeams($tab){

	$resultat = '<form id="formulaire" action="" method="POST">';
	$resultat .= '<select name="choixIdTeams">';
	for ($i=0;$i<count($tab);$i++) {			  
		$resultat .=	 '<option>'.$tab[$i]['idTeam'].'</option>';
	}
	$resultat .= '</select>';
	return $resultat;
}

// fonction qui va afficher toutes les opérations à effectuer sur la table daysofweek
function crud_teams($tab){
	$resultat = '	<form id="formulaire" action="?action=crud" method ="POST">
					<fieldset>
						<legend>Ajouter</legend>
					ID : 						'.increment_teamsID() .'<br>
					Label : 						<br><input type="text" name="labelInTeamsInput"><br>
					Age Min :					<br><input type="text" name="ageMinInTeamsInput"><br>
					Age Max : 						<br><input type="text" name="ageMaxInTeamsInput"><br>
					Godfather : 						<br><input type="text" name="godFatherInTeamsInput"><br>
					Ordre : 						<br><input type="text" name="ordreInTeamsInput"><br>
					Active : 					<br><input type="text" name="activeInTeamsInput"><br>
												<input type="submit" name="ajouterChampsInTeams" value="Ajouter"><br>
					</fieldset>
					<fieldset>
						<legend>Modifier</legend>
							ID TEAMS a modifier (EQUIPE CORRESPONDANT A ID SE TROUVE DANS LE TABLEAU EN BAS): '.select_idTeams(listeIdTeams()).'<br>
							New Label :  		<br><input type="text" name="newLabelTeams"><br>
							New Age Min : 	<br><input type="text" name="newAgeMinTeams"><br>
							New Age Max :			<br><input type="text" name="newAgeMaxTeams"><br>
							New Godfather :			<br><input type="text" name="newGodFatherTeams"><br>
							New Ordre :			<br><input type="text" name="newOrdreTeams"><br>
							New active : 		<br><input type="text" name="newActiveTeams"><br>
												<input type="submit" name="modifierChampsInTeams" value="Modifier">
					</fieldset>
					<table id="tableBalises">
						<thead>
							<tr>
								<th>ID</th>
								<th>EQUIPE</th>
								<th>Age Min</th>
								<th>Age Max</th>
								<th>Parrain</th>
								<th>Ordre</th>
								<th>Active</th>
								<th>Operation</th>
								</tr>
						</thead>
						<tbody>';
				 
	foreach($tab as $elt) {
		$resultat .=		'<tr>';
		$resultat .=		'<td>'.$elt['idTeam'].'</td>';
		$resultat .=		'<td>'.$elt['label'] .'</td>';
		$resultat .=		'<td>'.$elt['ageMin'] .'</td>';
		$resultat .=		'<td>'.$elt['ageMax'] .'</td>';
		$resultat .=		'<td>'.$elt['godFather'] .'</td>';
		$resultat .=		'<td>'.$elt['ordre'] .'</td>';
		$resultat .=		'<td>'.$elt['active'] .'</td>';
		if($elt['active'] == 1){
			$resultat .='<td><input type="submit" class="inactif" name="supprimerChampsInTeams" value="Rendre Inactif"><input type="radio"  name="idTeamTeams" value='.$elt['idTeam'].'>'.'</td>';
			}else{
			$resultat .='<td><input type="submit" class="actif" name="supprimerChampsInTeams" value="Rendre   Actif"><input type="radio"  name="idTeamTeams" value='.$elt['idTeam'].'>'.'</td>';
			}
		$resultat .=		'</tr>';	 
	}
		
	$resultat .= '	
					</tbody>
					</thead>
				   </table>
				   </form>';			   
	return $resultat;
}

/************************************************************************************************************************************************************************************/

/*
************************************************************TypeMatch*********************************************************************************************************
*/

function select_idTypeMatch($tab){

	$resultat = '<form id="formulaire" action="" method="POST">';
	$resultat .= '<select name="choixIdTypeMatch">';
	for ($i=0;$i<count($tab);$i++) {			  
		$resultat .=	 '<option>'.$tab[$i]['idTypeMatch'].'</option>';
	}
	$resultat .= '</select>';
	return $resultat;
}

// fonction qui va afficher toutes les opérations à effectuer sur la table daysofweek
function crud_typematchs($tab){
	$resultat = '	<form id="formulaire" action="?action=crud" method ="POST">
					<fieldset>
						<legend>Ajouter</legend>
					ID : 						<br><input type="text" name="IDTypeMatchInTypeMatchsInput"><br>
					Type de match : 			<br><input type="text" name="TypeMatchInTypeMatchsInput"><br>
												<input type="submit" name="ajouterChampsInTypeMatchs" value="Ajouter"><br>
					</fieldset>
					<fieldset>
						<legend>Modifier</legend>
							ID : '.select_idTypeMatch(listeIdTypeMatch()).'<br>
							New Type match :  	<br><input type="text" name="newTypeMatchTypeMatchs"><br>
												<input type="submit" name="modifierChampsInTypeMatchs" value="Modifier">
					</fieldset>
					<table id="tableBalises">
						<thead>
							<tr>
								<th>ID</th>
								<th>Type de match</th>
								<th>Operation</th>
								</tr>
						</thead>
						<tbody>';
				 
	foreach($tab as $elt) {
		$resultat .=		'<tr>';
		$resultat .=		'<td>'.$elt['idTypeMatch'].'</td>';
		$resultat .=		'<td>'.$elt['TypeMatch'] .'</td>';
		$resultat .='<td><input type="submit" name="supprimerChampsInTypesMatchs" value="Supprimer"><input type="radio"  name="idTypeMatchTypeMatchs" value='.$elt['idTypeMatch'].'></td>';
			
		$resultat .=		'</tr>';	 
	}
		
	$resultat .= '	
					</tbody>
					</thead>
				   </table>
				   </form>';			   
	return $resultat;
}

/************************************************************************************************************************************************************************************/


/***********************************************************************END OF CRUDPART1*****************************************************************************************/

/***********************************************************************CRUD PART2*****************************************************************************************/
 
/***********************************************************************TEAMSCOACHES*****************************************************************************************/
	
	
	function show_coaches_per_team($tab){
		$resultat  = '<form id="formulaire" action="?action=crud" method ="POST">';
		$resultat .= '<table id="tableBalises">
						<thead>
							<tr>
								<th>TEAM</th>
								<th>ID TEAM</th>
								<th>ID COACH</th>
								<th>COACHE(S)</th>
							</tr>
						</thead>
						<tbody>';
		$resultat .=		'<tr>';				
		$resultat .=		'<td rowspan="10">'.$tab[0]['Teams'].'</td>';
			   $id = '';
		foreach($tab as $elt) {
			   $id = $elt['idTeam'];
		$resultat .=		'<td>'.$elt['idTeam'].'</td>';
		$resultat .=		'<td>'.$elt['idCoach'].'</td>';
		$resultat .=		'<td><input type="radio" name="idCoachToDel" value='.$elt['idCoach'].'><input type="submit" name="delCoach" value="delete" class="actif"> '.$elt['Coach'] .'</td>';
		$resultat .=		'</tr>';	 
	}
		
	$resultat .= '	
					</tbody>
				   </table>	';
	$resultat .= '<hr>
					<legend>ADD A NEW COACH IN '.$tab[0]['Teams'].' </legend>
					<table id="tableBalises">
						<thead>
							<tr>
								<th>ID USER</th>
								<th>COACH</th>
								<th>MAIN COACH</th>
								<th>YEARTEAM</th>
							</tr>
						</thead>
						<tbody>';
						
	$tabCoachNotInTeam = coach_not_in_team();						
	foreach($tabCoachNotInTeam as $elt2){
		$resultat .= '<input type="hidden" name="nomDeLEquipe" value='.$id.'>';
		$resultat .= '<tr>';
		$resultat .= '<td>'.$elt2['idUser'].'</td>';		
		$resultat .= '<td><input type="radio" value='.$elt2['idUser'].' name="newCoach"><input type="submit" value="ADD" name="addNewCoach"  class="actif">'.$elt2['Coach'].'</td>';
		$resultat .= '<td><input type="text" name="newMainCoachTeam"></td>';
		$resultat .= '<td><input type="text" name="newYearTeamTeam"></td>';
		$resultat .= '</tr>';
	}				
					
	$resultat .=   '</tbody>
					</table>		   
				    </form>';
						
	return $resultat;
	}
	
	function afficher_coachs_par_equipes($tab){
		$resultat  = '	<form id="formulaire" action="?action=crud" method ="POST">';
		$resultat .=	'<p>Liste des equipes avec leurs entraineurs</p>';	
		$resultat .=	'<table id="tableBalises" >
						<thead>
							<tr>
								<th>IDTEAMCOACH</th>
								<th>ID TEAM</th>
								<th>Nom de l\'equipe</th>
								<th>ID USER</th>
								<th>ID COACH</th>
								<th>COACH</th>
								<th>YEAR TEAM</th>
								<th>MAIN COACH STATUS</th>
								<th>OPERATION</th>
								</tr>
						</thead>
						<tbody>';
		
		foreach($tab as $elt) {
		$resultat .=		'<tr>';
		$resultat .=		'<td>'.$elt['idTeamCoach'].'</td>';
		$resultat .=		'<td>'.$elt['idTeam'].'</td>';
		$resultat .=		'<td>'.$elt['Nom de l\'equipe'].'</td>';
		$resultat .=		'<td>'.$elt['ID USER'] .'</td>';
		$resultat .=		'<td>'.$elt['ID COACH'] .'</td>';
		$resultat .=		'<td>'.$elt['COACH'] .'</td>';
		$resultat .=		'<td>'.$elt['Annee de l\'equipe'] .'</td>';
		$resultat .=		'<td>'.$elt['MAIN COACH STATUS'] .'</td>';
		$resultat .=		'<td><input type="radio" name="nomDeLEquipe" value='.$elt['idTeam'].'><input type="submit" name="modifierTeamCoach" value="Modifier" class="actif"></td>';
		$resultat .=		'</tr>';	 
	}
		
	$resultat .= '	
					</tbody>
					</thead>
				   </table>
				   </form>';
	return $resultat;
	}
	
/****************************************************************************************************************************************************************************/
/**************************************************************TeamsCalendar*************************************************************************************************/
	function show_teams_calendar($tab){
		$resultat  = '	<form id="formulaire" action="?action=crud" method ="POST">
	                        <fieldset>
	                            <legend>ADD A NEW CALENDAR</legend>

	                 ';
        $teamToSelect = select_team();
        $resultat .= 'TEAM   ';
        $selectMenuTeam = '<select name="teamSelectedForCalendar">';
        for($i = 0; $i<count($teamToSelect); $i++) {
            $selectMenuTeam .=	 '<option>'.$teamToSelect[$i].'</option>';
        }
        $selectMenuTeam .= '</select>';
        $resultat .= $selectMenuTeam.'<br><br>';
        $resultat .= 'YEAR TEAM   <br><input type="text" name="newYearTeamInTeamsCalendarUpdate" ><br>';
        $resultat .= 'IN TEAM     <br><input type="text" name="newIndTeamInTeamsCalendarUpdate" ><br>';
        $resultat .= 'OUT TEAM    <br><input type="text" name="newOutTeamInTeamsCalendarUpdate" ><br>';
        $resultat .= 'SCORE IN    <br><input type="text" name="newScoreINInTeamsCalendarUpdate" ><br>';
        $resultat .= 'SCORE OUT   <br><input type="text" name="newScoreOUTInTeamsCalendarUpdate" ><br><br>';
        $resultat .= 'TYPE MATCH ';
        $typeMatchSelected = select_typeMatch_for_calendar();
        $selectMenuTypeMatch = '<select name="newTypeMatchInTeamsCalendarUpdate">';
        for($i = 0; $i<count($typeMatchSelected); $i++) {
            $selectMenuTypeMatch .=	 '<option>'.$typeMatchSelected[$i].'</option>';
        }
        $selectMenuTypeMatch .= '</select>';
        $resultat .= $selectMenuTypeMatch.'<br><br>';
        $resultat .= 'MODIFIED    <br><input type="text" name="newmodifiedInTeamsCalendarUpdate" ><br>';
        $resultat .= '#MATCH      <br><input type="text" name="newnumMatchInTeamsCalendarUpdate" ><br>';
        $resultat .= 'TIME MATCH  <br><input type="text" name="newTimeMatchInTeamsCalendarUpdate" ><br>';
        $resultat .= 'DATE MATCH  <br><input type="text" name="newDateMatchInTeamsCalendarUpdate" ><br>';
        $resultat .= '<input type="submit" name="addNewCalendar" value="ADD"><br>';
        $resultat .= '</fieldset>';
        $resultat .= '<p></p>';
        $resultat .=	'<table id="tableBalises" >
						<thead>
							<tr>
								<th>ID CALENDAR</th>
								<th>ID TEAM</th>
								<th>YEAR TEAM</th>
								<th>TEAM</th>
								<th>IN TEAM</th>
								<th>OUT TEAM</th>
								<th>SCORE IN</th>
								<th>SCORE OUT</th>
								<th>TYPE MATCH</th>
								<th>MODIFIED</th>
								<th>#MATCH</th>
								<th>TIME MATCH</th>
								<th>DATE MATCH</th>
								<th>OPERATION</th>
							</tr>
						</thead>
						<tbody>';
		
		foreach($tab as $elt) {
		$resultat .=		'<tr>';
		$resultat .=		'<td>'.$elt['idCalendar'].'</td>';
		$resultat .=		'<td>'.$elt['idTeam'].'</td>';
		$resultat .=		'<td>'.$elt['Year Team'].'</td>';
		$resultat .=		'<td>'.$elt['TEAM'] .'</td>';
		$resultat .=		'<td>'.$elt['IN TEAM'] .'</td>';
		$resultat .=		'<td>'.$elt['OUT TEAM'] .'</td>';
		$resultat .=		'<td>'.$elt['SCORE IN'] .'</td>';
		$resultat .=		'<td>'.$elt['SCORE OUT'] .'</td>';
		$resultat .=		'<td>'.$elt['TypeMatch'] .'</td>';
		$resultat .=		'<td>'.$elt['modified'] .'</td>';
		$resultat .=		'<td>'.$elt['#MATCH'] .'</td>';
		$resultat .=		'<td>'.$elt['TIME MATCH'] .'</td>';
		$resultat .=		'<td>'.$elt['DATE MATCH'] .'</td>';
		$resultat .=		'<td><input type="radio" name="idCalendarCRUD" value='.$elt['idCalendar'].'><input type="submit" name="modifierTeamCalendar" value="Modifier" class="actif"></td>';
		$resultat .=		'</tr>';	 
	}
		
		$resultat .= '	
					</tbody>
					</thead>
				   </table>
				   </form>';
		return $resultat;
	}
	
	function show_selected_team_calendar($tab){
		$resultat  = '	<form id="formulaire" action="?action=crud" method ="POST">';
		foreach($tab as $elt) {
			$resultat .= 'ID CALENDAR  <br><input type="text" name="YearTeamInTeamsCalendarUpdate" value='.$elt['idCalendar'].'><br><input type="hidden" name="idCalendarCRUD" value='.$elt['idCalendar'].'>';
			$resultat .= 'ID TEAM      <br><input type="text" name="YearTeamInTeamsCalendarUpdate" value='.$elt['idTeam'].'><br>';
			$resultat .= 'TEAM :       <br><input type="text" name="YearTeamInTeamsCalendarUpdate" value='.$elt['TEAM'].'><br>';
			$resultat .= 'YEAR TEAM   <br><input type="text" name="YearTeamInTeamsCalendarUpdate" value='.$elt['Year Team'].'><br>';
			$resultat .= 'IN TEAM     <br><input type="text" name="IndTeamInTeamsCalendarUpdate" value='.$elt['IN TEAM'].'><br>';
			$resultat .= 'OUT TEAM    <br><input type="text" name="OutTeamInTeamsCalendarUpdate" value='.$elt['OUT TEAM'].'><br>';
			$resultat .= 'SCORE IN    <br><input type="text" name="ScoreINInTeamsCalendarUpdate" value='.$elt['SCORE IN'].'><br>';
			$resultat .= 'SCORE OUT   <br><input type="text" name="ScoreOUTInTeamsCalendarUpdate" value='.$elt['SCORE OUT'].'><br>';
			$resultat .= 'TYPE MATCH  <br><input type="text" name="TypeMatchInTeamsCalendarUpdate" value='.$elt['TypeMatch'].'><br>';
			$resultat .= 'MODIFIED    <br><input type="text" name="modifiedInTeamsCalendarUpdate" value='.$elt['modified'].'><br>';
			$resultat .= '#MATCH      <br><input type="text" name="numMatchInTeamsCalendarUpdate" value='.$elt['#MATCH'].'><br>';
			$resultat .= 'TIME MATCH  <br><input type="text" name="TimeMatchInTeamsCalendarUpdate" value='.$elt['TIME MATCH'].'><br>';
			$resultat .= 'DATE MATCH  <br><input type="text" name="DateMatchInTeamsCalendarUpdate" value='.$elt['DATE MATCH'].'><br>';
		}
			$resultat .= '<input type="submit" value="UPDATE" name="updateCalendar">';
			$resultat .= '</form>';
		return $resultat;
	}
/****************************************************************************************************************************************************************************/

/**************************************************************TeamsDelegues*************************************************************************************************/
	$globalIdTeaminTeamDelegue = '';
	function afficher_delegue_par_team($tab){
		// $resultat = '	<form id="formulaire" action="?action=crud" method ="POST">';
		
		$resultat = '<p>Delegues par equipes</p>';
		$resultat .=	'<table id="tableBalises">
						<thead>
							<tr>
								<th>TEAM</th>
								<th>DELEGUE</th>
								<th>ID TEAMDELEGUE</th>
								<th>ID TEAM</th>
								<th>ID DELEGUE</th>
								<th>MAIN DELEGUE</th>
								<th>YEAR TEAM</th>
								<th>OPERATION</th>
							</tr>
						</thead>
						<tbody>';
						
			foreach($tab as $elt) {
				
				$GLOBALS['globalIdTeaminTeamDelegue'] = $elt['idTeam'];
				$resultat .=		'<tr>';
				$resultat .=		'<td>'.$elt['Team'].'</td>';
				$resultat .=		'<td>'.$elt['Delegue'].'</td>';
				$resultat .=		'<td>'.$elt['idTeamDelegue'].'</td>';
				$resultat .=		'<td>'.$elt['idTeam'].'</td><input type="hidden" name="idTeamForADDDelgue" value='.$GLOBALS['globalIdTeaminTeamDelegue'].'>';
				$resultat .=		'<td>'.$elt['idDelegue'] .'</td>';
				$resultat .=		'<td>'.$elt['mainDelegue'] .'</td>';
				$resultat .=		'<td>'.$elt['yearTeam'] .'</td>';
				$resultat .=		'<td><input type="radio" name="idTeamDelegueCRUD" value='.$elt['idTeamDelegue'].'><input type="submit" name="modifierTeamDelegues" 	value="Modifier" class="actif"></td>';
				$resultat .=		'</tr>';	
			}
			
			$resultat .= '	
					</tbody>
					</thead>
				   </table>';
				
		return $resultat;
	}
	
	function show_selected_team_delegue($tab){
		$resultat = '<div id="madiv">';
		if(isset($_POST['modifierTeamDelegues'])){
			$resultat .= '<input type="hidden" name="ok" value='.$_POST['idTeamDelegueCRUD'].'>';
			$delegueNotInTeam = delegue_to_add();
			$resultat .= '<fieldset>';
			$resultat .= '<legend>Delegue TO ADD AND NOT in '.$tab[0]['label'].' </legend>';
			$resultat .=	'<table id="tableBalises">
							<thead>
								<tr>
									<th>ID NEW DELEGUE</th>
									<th>DELEGUE</th>
									<th>OPERATION</th>
									</tr>
							</thead>
							<tbody>';
			foreach($delegueNotInTeam as $elt1) {
				$resultat .=		'<tr>';
				$resultat .=		'<td>'.$elt1['idUser'].'</td>';
				$resultat .=		'<td>'.$elt1['Delegue'].'</td>';
				$resultat .=		'<td><input type="radio" name="idDelegueToADD" value ='.$elt1['idUser'].'><input type="submit" name="addNewDelegue"	value="ADD" class="actif"><input type="hidden" name="idTeamNewDelegue" value='.$GLOBALS['globalIdTeaminTeamDelegue'].'></td>';
				$resultat .=		'</tr>';	
			}
			$resultat .= '	
					</tbody>
					</thead>
				   </table>';
			$resultat .= '</fieldset>';		 
				
		}		
		$resultat .= '</div>';
		$resultat .= '<br>';
		$resultat .= '<fieldset>';
		$resultat .= '<legend>UPDATE</legend>';
		foreach($tab as $elt) {
			$teamToSelect = select_team();
			$resultat .= 'TEAM  <br><input type="text" name="TeamInTeamsDelegueUpdate" value='.$elt['label'].' disabled><br>';
			$resultat .= 'NAME DELEGUE     				<br><input type="text" name="DelegueInTeamsDelegueUpdate" value='.$elt['name'].' disabled><br>';
			$resultat .= 'FIRSTNAME DELEGUE     		<br><input type="text" name="DelegueInTeamsDelegueUpdate" value='.$elt['firstname'].' disabled><br>';
			$resultat .= 'ID TEAMDELEGUE    			<br><input type="text" name="IdTeamDelegueInTeamsDelegueUpdate" value='.$elt['idTeamDelegue'].' disabled><br>';
			$resultat .= 'ID TEAM   					<br><input type="text" name="IdTeamInTeamsDelegueUpdate" value='.$elt['idTeam'].' disabled><br>';
			$resultat .= 'ID DELEGUE     				<br><input type="text" disabled><br>';
			$resultat .= '<input type="hidden" value='.$elt['idDelegue'].' name="IdDelegueInTeamsDelegueUpdate">';
			$resultat .= 'MAIN DELEGUE   				<br><input type="text" name="MainDelegueInTeamsDelegueUpdate" value='.$elt['mainDelegue'].' ><br>';
			$resultat .= 'YEAR TEAM   					<br><input type="text" name="YearTeamInTeamsDelegueUpdate" value='.$elt['yearTeam'].'><br>';
			$resultat .= '<input type="hidden" name="idTeamDelegueUpDate" value='.$elt['idTeamDelegue'].'>';
		}
		$resultat .= '<p><input type="submit" value="UPDATE" name="updateDelegue"></p>';
		$resultat .= '</fieldset>';	
		// $resultat .= '</form>';
		return $resultat;
	}
/****************************************************************************************************************************************************************************/

/**************************************************************************TeamsRanking**************************************************************************************/
	function afficher_TeamsRanking($tab){
			$resultat = '';
			$resultat .= '<fieldset><legend>ADD A NEW RANKING</legend>';
			$teamToSelect = select_team();
			$resultat .= 'TEAM <br>';
			$selectMenuTeam = '<select name="teamSelectedForRanking">';
				for($i = 0; $i<count($teamToSelect); $i++) {
					$selectMenuTeam .=	 '<option>'.$teamToSelect[$i].'</option>';
				}
			$selectMenuTeam .= '</select>';
        $resultat .= $selectMenuTeam.'<br><br>';
			$resultat .= 'NEW YEAR :       	 <br><input type="text" name="NEWyearInRankingUpdate" ><br>';
			$resultat .= 'NEW PLAYED       	 <br><input type="text" name="NEWplayedInRankingUpdate"><br>';
			$resultat .= 'NEW WIN   	   	 <br><input type="text" name="NEWwinInRankingUpdate"><br>';
			$resultat .= 'NEW LOST   	   	 <br><input type="text" name="NEWlostInRankingUpdate"><br>';
			$resultat .= 'NEW DEUCE  	   	 <br><input type="text" name="NEWdeuceInRankingUpdate"><br>';
			$resultat .= 'NEW POINTS 	   	 <br><input type="text" name="NEWpointsInRankingUpdate"><br>';
			$resultat .= 'NEW DATE RANKING   <br><input type="text" name="NEWdateRankingUpdate"> YYYY-MM-DD<br>';
		$resultat .= '<input type="submit" value="ADD" name="addRanking">';
		$resultat .= '</fieldset>';
		
		$resultat .= '<fieldset><legend>Resultats des TEAMS</legend>';
		$resultat .=	'<table id="tableBalises">
						<thead>
							<tr>
								<th>ID RANKING</th>
								<th>ID TEAM</th>
								<th>YEAR</th>
								<th>TEAM</th>
								<th>PLAYED</th>
								<th>WIN</th>
								<th>LOST</th>
								<th>DEUCE</th>
								<th>POINTS</th>
								<th>DATE RANKING</th>
								<th>OPERATION</th>
							</tr>
						</thead>
						<tbody>';
						
			foreach($tab as $elt) {
				$resultat .=		'<tr>';
				$resultat .=		'<td>'.$elt['idRanking'].'</td>';
				$resultat .=		'<td>'.$elt['idTeam'].'</td>';
				$resultat .=		'<td>'.$elt['myYear'].'</td>';
				$resultat .=		'<td>'.$elt['name'].'</td>';
				$resultat .=		'<td>'.$elt['played'] .'</td>';
				$resultat .=		'<td>'.$elt['win'] .'</td>';
				$resultat .=		'<td>'.$elt['lost'] .'</td>';
				$resultat .=		'<td>'.$elt['deuce'] .'</td>';
				$resultat .=		'<td>'.$elt['points'] .'</td>';
				$resultat .=		'<td>'.$elt['dateRanking'] .'</td>';
				$resultat .=		'<td><input type="radio" name="idRanking" value='.$elt['idRanking'].'><input type="submit" name="modifierTeamsRanking" value="Modifier" class="actif"></td>';
				$resultat .=		'</tr>';	
			}
			
			$resultat .= '	
					</tbody>
					</thead>
				   </table>';
			
			 $resultat .=	'</fieldset>';
			
				
		return $resultat;
	}
	
	function afficher_selected_team($tab){
		$resultat = '<div>';
		$resultat .= '<div  class="block">';
		foreach($tab as $elt) {
			$resultat .= 'ID RANKING  <br><input type="text" name="idRankingUpdate" value='.$elt['idRanking'].' disabled><br><input type="hidden" name="idRankingUpdateCRUD" value='.$elt['idRanking'].'>';
			$resultat .= 'ID TEAM      <br><input type="text" name="idTeaminRankingUpdate" value='.$elt['idTeam'].' disabled><br><input type="hidden" name="idTeamInRankingUpdateCRUD" value='.$elt['idTeam'].'>';
			$resultat .= 'YEAR :       <br><input type="text" name="yearInRankingUpdate" value='.$elt['myYear'].'><br>';
			$resultat .= 'NAME  <br><input type="text" name="nameInRankingUpdate" value='.$elt['name'].' disabled><br>';
			$resultat .= 'PLAYED     <br><input type="text" name="playedInRankingUpdate" value='.$elt['played'].'><br>';
			$resultat .= 'WIN   <br><input type="text" name="winInRankingUpdate" value='.$elt['win'].'><br>';
			$resultat .= 'LOST   <br><input type="text" name="lostInRankingUpdate" value='.$elt['lost'].'><br>';
			$resultat .= 'DEUCE  <br><input type="text" name="deuceInRankingUpdate" value='.$elt['deuce'].'><br>';
			$resultat .= 'POINTS <br><input type="text" name="pointsInRankingUpdate" value='.$elt['points'].'><br>';
			$resultat .= 'DATE RANKING   <br><input type="text" name="dateRankingUpdate" value='.$elt['dateRanking'].'><br>';
			
		}
		$resultat .= '<input type="submit" value="UPDATE" name="updateRanking">';
		$resultat .= '</div>';
		
		
		$resultat .= '</div>';	
		return $resultat;
	}
/****************************************************************************************************************************************************************************/

/**************************************************************************TeamsTraining*************************************************************************************/
	function afficher_TeamsTraining($tab){
			$resultat = '';
			$resultat .= '<fieldset><legend>ADD NEW TRAINING</legend>';
			
			$teamToSelect = select_team();
			$resultat .= 'TEAM <br>';
			$selectMenuTeam = '<select name="teamSelectedForTraining">';
				for($i = 0; $i<count($teamToSelect); $i++) {
					$selectMenuTeam .=	 '<option>'.$teamToSelect[$i].'</option>';
				}
			$selectMenuTeam .= '</select>';
			$resultat .= $selectMenuTeam.'<br><br>';
		
			$dayToSelect = select_day();
			$resultat .= 'DAY <br>';
			$selectMenuDay = '<select name="daySelectedForTraining">';
				for($i = 0; $i<count($dayToSelect); $i++) {
					$selectMenuDay .=	 '<option>'.$dayToSelect[$i].'</option>';
				}
			$selectMenuDay .= '</select>';
			$resultat .= $selectMenuDay.'<br><br>';
			
			$resultat .= 'NEW YEAR :       	 	 <br><input type="text" name="NEWyearInTrainingUpdate" ><br>';
			$resultat .= 'NEW START TIME       	 <br><input type="text" name="NEWstartInTrainingUpdate"><br>';
			$resultat .= 'NEW END TIME   	   	 <br><input type="text" name="NEWendInTrainingUpdate"><br>';
			$resultat .= 'NEW ROOM   	   	  	 <br><input type="text" name="NEWroomInTrainingUpdate"><br>';
			
		$resultat .= '<input type="submit" value="ADD" name="addTraining">';
		$resultat .= '</fieldset>';
		
		$resultat .= '<fieldset><legend>Entrainements par equipes</legend>';
		$resultat .=	'<table id="tableBalises">
						<thead>
							<tr>
								<th>ID TRAINING</th>
								<th>ID TEAM</th>
								<th>TEAM</th>
								<th>CURRENT YEAR</th>
								<th> ID DAY OF WEEK</th>
								<th>DAY</th>
								<th>START TIME</th>
								<th>END TIME</th>
								<th>ROOM</th>
								<th>OPERATION</th>
							</tr>
						</thead>
						<tbody>';
						
			foreach($tab as $elt) {
				$resultat .=		'<tr>';
				$resultat .=		'<td>'.$elt['idTraining'].'</td>';
				$resultat .=		'<td>'.$elt['idTeam'].'</td>';
				$resultat .=		'<td>'.$elt['Team'].'</td>';
				$resultat .=		'<td>'.$elt['currentYear'].'</td>';
				$resultat .=		'<td>'.$elt['dayOfWeek'] .'</td>';
				$resultat .=		'<td>'.$elt['label'] .'</td>';
				$resultat .=		'<td>'.$elt['startTime'] .'</td>';
				$resultat .=		'<td>'.$elt['endTime'] .'</td>';
				$resultat .=		'<td>'.$elt['room'] .'</td>';
				$resultat .=		'<td><input type="radio" name="idTrainingTeamsTraining" value='.$elt['idTraining'].'><input type="submit" name="modifierTeamsTraining" value="Modifier" class="actif"></td>';
				$resultat .=		'</tr>';	
			}
			
			$resultat .= '	
					</tbody>
					</thead>
				   </table>';
			
			 $resultat .=	'</fieldset>';	
				
		return $resultat;
	}
	
	function afficher_selected_teamTraining($tab){
		$resultat = '<div>';
		$resultat .= '<div  class="block">';
		foreach($tab as $elt) {
			$resultat .= 'ID TRAINING  <br><input type="text" name="idTrainingUpdate" value='.$elt['idTraining'].' disabled><br><input type="hidden" name="idTrainingUpdateCRUD" value='.$elt['idTraining'].'>';
			$resultat .= 'ID TEAM      <br><input type="text" name="idTeaminTrainingUpdate" value='.$elt['idTeam'].' disabled><br><input type="hidden" name="idTeamInTrainingUpdateCRUD" value='.$elt['idTeam'].'>';
			$resultat .= 'TEAM :       <br><textarea readonly name="labelTeamTrainingUpdate" style="width: 143px; height: 16px;">'.$elt['Team'].'</textarea><br>';
			$resultat .= 'CURRENT YEAR  <br><input type="text" name="currentYearInTrainingUpdate" value='.$elt['currentYear'].' disabled><br>';
			$resultat .= 'ID DAY     <br><input type="text" name="idDayInTrainingUpdate" value='.$elt['dayOfWeek'].' disabled><br>';
			$resultat .= 'DAY   <br><input type="text"  value='.$elt['label'].' disabled><br>';
			$resultat .= 'START TIME   <br><input type="text" name="startTimeTrainingUpdate" value='.$elt['startTime'].'><br>';
			$resultat .= 'END TIME  <br><input type="text" name="endTimeTrainingUpdate" value='.$elt['endTime'].'><br>';
			$resultat .= 'ROOM <br><textarea name="roomTrainingUpdate" style="width: 194px; height: 17px;">'.$elt['room'].'</textarea><br>';
			
		}
		$resultat .= '<input type="submit" value="UPDATE" name="updateTraining">';
		$resultat .= '</div>';
		
		
		$resultat .= '</div>';	
		return $resultat;
	}
	
/****************************************************************************************************************************************************************************/


/**************************************************************************TeamsGames*************************************************************************************/
	function afficher_TeamsGames($tab){
			$resultat = '';
			$resultat .= '<fieldset class="block"><legend>ADD NEW GAMES</legend>';
			
			$teamToSelect = select_team();
			$resultat .= 'TEAM <br>';
			$selectMenuTeam = '<select name="teamSelectedForGames">';
				for($i = 0; $i<count($teamToSelect); $i++) {
					$selectMenuTeam .=	 '<option>'.$teamToSelect[$i].'</option>';
				}
			$selectMenuTeam .= '</select>';
			$resultat .= $selectMenuTeam.'<br><br>';
		
			$dayToSelect = select_day();
			$resultat .= 'DAY <br>';
			$selectMenuDay = '<select name="daySelectedForGames">';
				for($i = 0; $i<count($dayToSelect); $i++) {
					$selectMenuDay .=	 '<option>'.$dayToSelect[$i].'</option>';
				}
			$selectMenuDay .= '</select>';
			$resultat .= $selectMenuDay.'<br><br>';
			
			$resultat .= 'NEW YEAR :       	 	 <br><input type="text" name="NEWyearInGamesUpdate" ><br>';
			$resultat .= 'NEW GAME TIME :        <br><input type="text" name="NEWgameTimeInGamesUpdate" ><br>';
			
		$resultat .= '<input type="submit" value="ADD" name="addGames">';
		$resultat .= '</fieldset>';
		
		$resultat .= '<fieldset><legend>MATCH par equipes</legend>';
		$resultat .=	'<table id="tableBalises">
						<thead>
							<tr>
								<th>ID TEAM GAME</th>
								<th>ID TEAM</th>
								<th>TEAM</th>
								<th>CURRENT YEAR</th>
								<th>ID GAME DAY</th>
								<th>DAY</th>
								<th>GAME TIME</th>
								<th>OPERATION</th>
							</tr>
						</thead>
						<tbody>';
						
			foreach($tab as $elt) {
				$resultat .=		'<tr>';
				$resultat .=		'<td>'.$elt['idTeamGame'].'</td>';
				$resultat .=		'<td>'.$elt['idTeam'].'</td>';
				$resultat .=		'<td>'.$elt['Team'].'</td>';
				$resultat .=		'<td>'.$elt['currentYear'].'</td>';
				$resultat .=		'<td>'.$elt['gameDay'] .'</td>';
				$resultat .=		'<td>'.$elt['label'] .'</td>';
				$resultat .=		'<td>'.$elt['gameTime'] .'</td>';
				$resultat .=		'<td><input type="radio" name="idTeamGameTeamsGames" value='.$elt['idTeamGame'].'><input type="submit" name="modifierTeamsGames" value="Modifier" class="actif"></td>';
				$resultat .=		'</tr>';	
			}
			
			$resultat .= '	
					</tbody>
					</thead>
				   </table>';
			
			 $resultat .=	'</fieldset>';	
				
		return $resultat;
	}
	
	function afficher_selected_teamGames($tab){
		$resultat = '<div>';
		$resultat .= '<fieldset><legend>UPDATE</legend>';
		foreach($tab as $elt) {
			$resultat .= 'ID TEAM GAME  <br><input type="text" name="idTeamGameUpdate" value='.$elt['idTeamGame'].' disabled><br><input type="hidden" name="idTeamGameUpdateCRUD" value='.$elt['idTeamGame'].'>';
			$resultat .= 'ID TEAM      <br><input type="text" name="idTeaminGamesUpdate" value='.$elt['idTeam'].' disabled><br><input type="hidden" name="idTeamInGamesUpdateCRUD" value='.$elt['idTeam'].'>';
			$resultat .= 'TEAM :       <br><textarea readonly name="labelTeamGamesUpdate" style="width: 143px; height: 16px;">'.$elt['Team'].'</textarea><br>';
			$resultat .= 'CURRENT YEAR  <br><input type="text" name="currentYearInGamesUpdate" value='.$elt['currentYear'].' ><br>';
			$resultat .= 'ID DAY     <br><input type="text" name="idDayInGamesUpdate" value='.$elt['gameDay'].' disabled><br>';
			$resultat .= 'DAY   <br><input type="text"  value='.$elt['label'].' disabled><br>';
			$resultat .= 'GAME TIME   <br><input type="text" name="gameTimeGamesUpdate" value='.$elt['gameTime'].'><br>';
			$resultat .= '</textarea><br>';
			
		}
		$resultat .= '<input type="submit" value="UPDATE" name="updateGames">';
		$resultat .= '</fieldset>';
		
		
		$resultat .= '</div>';	
		return $resultat;
	}
	
/****************************************************************************************************************************************************************************/


// Fonction qui va afficher le contenue de la table teamsplayers qui contient des joueurs inconnues si il y'en a
function afficher_joueurs_Inconnues($tab){
	if(count($tab)== 0)
		return "Tous les joueurs de teamsplayers se trouvent dans players (pas de clandestins ouff..) !";
	
	$tableau = '<table id="tableBalises">
				  <thead>
					<tr>
						<th>ID du joueur</th>
					</tr>
				  </thead>
			      <tbody>';
				 
	for ($i=0;$i<count($tab);$i++) {
		$tableau .=		'<tr>';
		$tableau .=		'<td>'.$tab[$i]['idPlayer'] .'</td>';
		$tableau .=		'</tr>';
						
	 
	}
	$tableau .= '</tbody>
					</thead>
				   </table>';
	return $tableau;
}

// Fonction qui va afficher les coachs de la table teamscoachs qui ne sont pas dans users
function afficher_coachs_Inconnues($tab){
	if(count($tab)== 0)
		return "Tous les coachs de teamscoachs se trouvent dans coachs (pas de clandestins ouff..) !";
	
	$tableau = '<table id="tableBalises">
				  <thead>
					<tr>
						<th>ID du coach</th>
					</tr>
				  </thead>
			      <tbody>';
				 
	for ($i=0;$i<count($tab);$i++) {
		$tableau .=		'<tr>';
		$tableau .=		'<td>'.$tab[$i]['idCoach'] .'</td>';
		$tableau .=		'</tr>';
						
	 
	}
	$tableau .= '</tbody>
					</thead>
				   </table>';
	return $tableau;
}

// Fonction qui va afficher les types de matchs  de la table teamsc qui ne sont pas dans users
function afficher_typeMatch_Inconnues($tab){
	if(count($tab)== 0)
		return "Tous les coachs de teamscoachs se trouvent dans coachs (pas de clandestins ouff..) !";
	
	$tableau = '<table id="tableBalises">
				  <thead>
					<tr>
						<th>Label du type de match inconnues</th>
					</tr>
				  </thead>
			      <tbody>';
				 
	for ($i=0;$i<count($tab);$i++) {
		$tableau .=		'<tr>';
		$tableau .=		'<td>'.$tab[$i]['TypeMatch'] .'</td>';
		$tableau .=		'</tr>';
						
	 
	}
	$tableau .= '</tbody>
					</thead>
				   </table>';
	return $tableau;
}

// Fonction qui va afficher les idUser dans role n'existant pas dans users
function afficher_idUser_role_Inconnues($tab){
	if(count($tab)== 0)
		return "Tous les idUser dans roles";
	
	$tableau = '<table id="tableBalises">
				  <thead>
					<tr>
						<th>idRole dans roles absent dans users</th>
					</tr>
				  </thead>
			      <tbody>';
				 
	for ($i=0;$i<count($tab);$i++) {
		$tableau .=		'<tr>';
		$tableau .=		'<td>'.$tab[$i]['idUser'] .'</td>';
		$tableau .=		'</tr>';
						
	 
	}
	$tableau .= '</tbody>
					</thead>
				   </table>';
	return $tableau;
}

function afficher_Mail_Incorrectes_USERS($tabUsers){
	if(count($tabUsers)== 0)
		return "Mail valide";
	$tableau = '<table id="tableBalises">
				  <thead>
					<tr>
						<th>Mail incorrectes dans users</th>
					</tr>
				  </thead>
			      <tbody>';
				 
	for ($i=0;$i<count($tabUsers);$i++) {
		$tableau .=		'<tr>';
		$tableau .=		'<td>'.$tabUsers[$i]['mail'] .'</td>';
		$tableau .= 	'</tr>';
	}
	$tableau .= '</tbody>
					</thead>
				   </table>';
	return $tableau;
}

function afficher_Mail_Incorrectes_PLAYERS($tabPlayers){
	if(count($tabPlayers)== 0)
		return "Mail valide";
	$tableau = '<table id="tableBalises">
				  <thead>
					<tr>
						<th>Mail incorrectes dans players</th>
					</tr>
				  </thead>
			      <tbody>';
				 
	for ($i=0;$i<count($tabPlayers);$i++) {
		$tableau .=		'<tr>';
		$tableau .=		'<td>'.$tabPlayers[$i]['email'] .'</td>';
		$tableau .= 	'</tr>';
	}
	$tableau .= '</tbody>
					</thead>
				   </table>';
	return $tableau;
}
?>